### ISSUE TITLE
Test Android Activity backgrounding

### ISSUE THREAD

**Issue by purplecabbage** [phonegap/phonegap-plugin-multiview#28]
We need to be sure that if the application root (parent) CordovaActivity is unloaded while displaying the child CordovaActivity we can still get results back, and restore our state.

The approach required is well documented here:
http://cordova.apache.org/docs/en/dev/guide/platforms/android/index.html#lifecycle-guide

**Comment by sterlingann** [comment]
1) my first approach was to create a test class that used ActivityLifeCycleCallBacks to count the number of activities present in the foreground and background.  While this worked just fine in Android Land, I could not successfully implement this in Cordova Land.
2) my second approach was to just manually check and see if onPause and onResume were called when an activity goes to the foreground or background.   I was feeling really good about this until I realized that the "dont keep activities box" in the developer options of my device was not actually checked....
3) Checking that box is important because it lets you deterministically test how your app behaves in the wild, ex: you have low memory issues .

After a day of unsuccessful test writing for this unique case and playing around in Android I have concluded that this is indeed an issue that must be fixed.
